<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="PrivateChat.aspx.cs" Inherits="NetDisc.PrivateChat" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="Scripts/layui/css/layui.css" rel="stylesheet" />
    <link href="Scripts/layui/css/layim.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="width:900px; margin:0 auto">
        <div class="layui-layer-title" style="height:100px;text-align:center" >
            <asp:Image ID="chatroom" runat="server" ImageUrl="Icon/4.png" Height="100px" Width="200px"/> </div>     
        <div class="layim-chat-box" > <div class="layim-chat layim-chat-friend layui-show">
        <div style="display:none">
            <asp:Image id="image" runat="server"  Height="55px" Width="64px"  /></div>   
        <div class="layim-chat-main" style="height: 450px;">
            <ul id="messageList" ></ul></div>
        <div class="layim-chat-footer">
             <div class="layim-chat-textarea">
                <textarea id="message"  class="layui-textarea" style="max-width:100%"/></textarea>
             </div> 
        <div class="layim-chat-bottom">
        <div class="layim-chat-send">
            <span class="layim-send-btn" id="send" layim-event="send" />Send</span>
            <input type="hidden" id="name" /> 
        </div>
        <div style="margin-top: 6px; float: left;">
            <select id="box">    <!--此处选择聊天对象,可改效果-->
                <option value="all">All</option>
            </select>
        </div>
        </div> </div> </div> </div> 

    <div id="chatList" >   <!--此处取在线好友,改布局及效果-->
        <p>OnlineUser</p>
        <ul id="list"></ul>
    </div> 

    <div style="display:none">
        <asp:Label ID="UserName" runat="server"></asp:Label>
    </div>
    </div>

<!--Reference the SignalR library. -->
<script src="Scripts/jquery-3.3.1.min.js" ></script>
<script src="../../Scripts/jquery.signalR-2.2.2.min.js" type="text/javascript"></script>
<!--Reference the autogenerated SignalR hub script. -->
<script src="../../signalr/hubs"></script>
<script type="text/javascript">
    var userID = "";

    $(function () {
        //回车查询
        var $inp = $('input:text');
        $inp.bind('keydown', function (e) {
            var key = e.which;
            if (key == 13) {
                $('#send').click();
            }
        });

        const un = '<%= Session["UserName"] %>';
        $('#UserName').val(un);//此处取用户SESSION！
        userID = $('#UserName').val();
        //建立与Server端的Hub的物件，Hub字母为小写！
        var chat = $.connection.chatHub;
        //取得所有上线清单
        chat.client.getList = function (userList) {
            var li = "";
            $.each(userList, function (index, data) {
                li += "<li id='" + data.id + "'>" + data.name + "</li>";   
            });
            $("#list").html(li);
            $.each(userList, function (index, data) {
                $("#box").append("<option value='" + data.id + "'>" + data.name + "</option>")
                $('#box').selectpicker('render');
                $('#box').selectpicker('refresh');    
            });  
        }

        //新增上线人员
        chat.client.addList = function (id, name) {
            var li = "<li id='" + id + "'>" + name + "</li>";
            $("#list").append(li);                            
            $("#box").append("<option value='" + id + "'>" + name + "</option>")
            $('#box').selectpicker('render');
            $('#box').selectpicker('refresh');
        }


        //全体聊天
        chat.client.sendAllMessge = function (message, name) {

            var encodedName = $('<div />').text(name).html();
            var encodedMsg = $('<div />').text(message).html();
            if (name == $('#UserName').val()) {
                $('#messageList').append('<li class="layim-chat-mine"><div class="layim-chat-user"><img src="Icon/3.png"/><cite><i>' + getNowFormatDate() + '</i>' + encodedName +
                    '</cite></div> <div class="layim-chat-text">' + encodedMsg + '</div> </li >');
            }
            else {
                $('#messageList').append('<li><div class="layim-chat-user"><img src="Icon/4.png"/><cite>' + encodedName + ' [secrect] '+ getNowFormatDate() + '<i>' //bug here
                    + '</i></cite></div><div class="layim-chat-text">' + encodedMsg + '</div></li>');
            }


          //  $("#messageList").append("<li>" + message + "</li>");
        }

        //私密聊天
        chat.client.sendMessage = function (message, name) {
            var encodedName = $('<div />').text(name).html();
            var encodedMsg = $('<div />').text(message).html();
            if (name == $('#UserName').val()) {
                $('#messageList').append('<li class="layim-chat-mine"><div class="layim-chat-user"><img src="Icon/3.png"/><cite><i>' + getNowFormatDate() + '</i>' + encodedName+' [secrect] '+
                    '</cite></div> <div class="layim-chat-text">' + encodedMsg+ '</div> </li >');
            }
            else {
                $('#messageList').append('<li><div class="layim-chat-user"><img src="Icon/4.png"/><cite>' + encodedName + ' [secrect] '+getNowFormatDate() + '<i>' //bug here
                    + '</i></cite></div><div class="layim-chat-text">' + encodedMsg + '</div></li>');
            }
           // $("#messageList").append("<li>" + message+name+ "</li>");
        }

     /*   chat.client.hello = function (message) {
            $("#messageList").append("<li>" + message + "</li>");
        } */

       
        $.connection.hub.start().done(function () {
           
            chat.server.userConnected(userID);
        });;

        $("#send").click(function () {
            var to = $("#box").val();
            //all 为全体，否则为私密
            if (to == "all") {
                chat.server.sendAllMessage($("#message").val());
            } else {
                chat.server.sendMessage(to, $("#message").val());
            }
            $("#message").val('');
        });


    });
    function getNowFormatDate() {
        var date = new Date();
        var seperator1 = "-";
        var seperator2 = ":";
        var month = date.getMonth() + 1;
        var strDate = date.getDate();
        if (month >= 1 && month <= 9) {
            month = "0" + month;
        }
        if (strDate >= 0 && strDate <= 9) {
            strDate = "0" + strDate;
        }
        var currentdate = date.getFullYear() + seperator1 + month + seperator1 + strDate
            + " " + date.getHours() + seperator2 + date.getMinutes()
            + seperator2 + date.getSeconds();
        return currentdate;
    }
</script>
</asp:Content>
